name: Autograder

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest_version # Replace with the actual latest version
    - name: Set up Python
      uses: actions/setup-python@latest_version # Replace with the actual latest version
      with:
        python-version: '3.x'
        node-version: '20' # This line is hypothetical; check if such an option exists
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest
    - name: Run tests
      run: |
        python test_lab.py